name: "Process results"
description: "Process test and coverage results"
inputs:
  test_results:
    description: "Test results file"
    default: "test.out"
  coverage_profile:
    description: "Coverage profile file"
    default: "cover.out"
  with_archive:
    description: "Attaches html coverage results as job artifact"
    default: "false"
  github_token:
    description: "Github token write pull request scope"
    default: "${{ github.token }}"
  cleanup:
    description: "Cleanup workspace"
    default: "true"
runs:
  using: "composite"
  steps:
    - name: process results
      run: ${{ github.action_path }}/summary.sh
      env:
        TEST_RESULT_LOG: ${{ inputs.test_results }}
        COVERAGE_PROFILE: ${{ inputs.coverage_profile }}
        WITH_ARCHIVE: ${{ inputs.with_archive }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_NODE_ID: ${{ github.event.pull_request.node_id }}
      shell: bash
    - name: Archive code coverage results
      if: inputs.with_archive == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.html
        retention-days: 5
    - name: Cleanup
      if: inputs.cleanup == 'true'
      run: ${{ github.action_path }}/cleanup.sh
      shell: bash
